### ISSUE TITLE
Example in readme broken (missing a closing ')

### ISSUE THREAD

**Issue by JVSemmelrock** [StartAutomating/EZOut#1]
The sample is missing the single quote to close -TypeName parameter.

Current 
> Write-FormatView -TypeName 'System.Management.ManagementObject#root\cimv2\Win32_VideoController

Should be
> Write-FormatView -TypeName 'System.Management.ManagementObject#root\cimv2\Win32_VideoController'

**Comment by StartAutomating** [comment]
Overhauled documentation, removing this example as a byproduct.
