### ISSUE TITLE
[Enhancement] Prevent Auto Format On Certain Types

### ISSUE THREAD

**Issue by mattcargile** [StartAutomating/EZOut#47]
It would be convenient to be able to pick and choose which formatters we want to be applied in the below code. For instance, I'm not into tree view for `FileInfo`. I really like the `[xml]` formatter though. Maybe something like `ModuleArguments`?

https://github.com/StartAutomating/EZOut/blob/21cf8871f28536b2d5d4ece5d162c70c62a3d637/EZOut.psm1#L96

**Comment by StartAutomating** [comment]
@mattcargile 

I have been meaning to separate out the formatting that EZOut builds into another module.  I'll make sure to incorporate this suggestion whenever I get around to that, and will bump the priority.

**Comment by StartAutomating** [comment]
@mattcargile As I haven't gotten around to creating a separate module yet, and am also not a huge fan of some of the problems in the file tree formatter, I'm adding a table formatter for files that is similar to the built-in formatter, with two nifty differences:

* It Does not include a Mode Column
* It Lists Length in gb/mb/kb or bytes

If you feel that this isn't good enough, please let me know and we'll reopen this issue.
