### ISSUE TITLE
Add a Write-FormatControl command

### ISSUE THREAD

**Issue by vexx32** [StartAutomating/EZOut#8]
Currently there are (at least) 2 ways to write a format control:

```ps1
Write-FormatView -TypeName typename -AsControl -Name ControlName -Action { }
```
This requires both an `-AsControl` switch and a `-TypeName` to be specified, although the `-TypeName` is completely ignored.

```ps1
Write-FormatCustomView -AsControl -Name ControlName -Action { }
```

This is better, but still not much shorter.

Why not have this as the preferred method:

```ps1
Write-FormatControl -Name ControlName -Action { }
```

**Comment by StartAutomating** [comment]
Included in recent PR #9
